### PR TITLE
fix-16 enforcing standard code style

### LINKED ISSUE #16: Enforcing standard code style
As we implemented Prettier in our central repository. Similarly, we can do it here.

### PR DESCRIPTION
**Pull request by rahul799**
fix #16

### CODE REVIEW

**Comment by rahul799** [comment]
@robkooper am not sure that which files are auto-generated. Please let me know.

**Comment by robkooper** [comment]
Created a new issue #18 wrt to all the documentation generated by pkgdown in base/*/docs.

**Comment by mdietze** [comment]
I think almost 100% of this is machine generated, in which case it's not clear to me we want to "pretty" it. I'll leave the decision to pull or not to @robkooper

**Comment by dlebauer** [comment]
obsolete, from old version of the website

**Pull request closed without merging**
