### PR TITLE
Moved old demos to end

### PR DESCRIPTION
**Pull request by dlebauer**
This was a changed suggested by a user who did not ever make it to either the video or the vignettes, but would have found them useful.

### CODE REVIEW

**Comment by mdietze** [comment]
I don't want the video on top -- it's dangerously out dated (>3.5 years), which is why it's at the bottom. Once @tonygardella starts making new and up-to-date video tutorials I agree that these should be more prominent.

**Comment by dlebauer** [comment]
@mdietze should there be a disclaimer about it being out of date? Last time I watched it (admittedly a while ago) it there was a good conceptual overview, most of which would still be relevant.

**Comment by mdietze** [comment]
I think the age of the video, which is listed, already implies that it's not necessarily up to date

**Comment by dlebauer** [comment]
closing as waaaay out of date

**Pull request closed without merging**
